### ISSUE TITLE
Question on building the URL

### ISSUE THREAD

**Issue by vphimmasone** [mndrix/sms-over-xmpp#21]
Hi,
This is not a question about an issue :) . I installed the application sms-over-xmpp . create an account on twillio , generating the key etc ... and even built a prosody xmpp server .
However i can't find the connection  between Twilio and sms-over-xmpp . It mention a http request to my server but how to redirect the request to sms-over-xmpp directory , is it a specific directory or file ?
Note: i'm new into this environment :) any help would be great 

Thanks
Vanna

**Comment by mndrix** [comment]
On Thu, Nov 16, 2017, 6:16 PM vphimmasone <notifications@github.com> wrote:

> but how to redirect the request to sms-over-xmpp directory
>
Hi Vanna. That step depends greatly on details specific to your server. I
personally use haproxy to route Twilio's incoming HTTP requests to my
running instance of sms-over-xmpp. I have haproxy rules that route other
HTTP requests to other processes on my server.

Sorry that I couldn't be more help.

>

**Comment by vphimmasone** [comment]
Thank you sir for your answer ! So basically i added a on my Twillio SMS account a HTTP POST:

https://my.server.com/sms-over-xmpp 

Is this something like that ?

Vanna

**Comment by mndrix** [comment]
That sounds about right
