### ISSUE TITLE
Twilio 502 error

### ISSUE THREAD

**Issue by JamesB7** [mndrix/sms-over-xmpp#22]
Hello,

Twilio's debugger is giving me:

Twilio was unable to fetch content from: (my url)
Error: Error reading response: Response does not contain content type

I have it set up as a Webhook. Messages are still delivering. Twilio is just reporting an error for every message. Any idea?

Thanks!

James

**Comment by mndrix** [comment]
That is puzzling. It sounds like the HTTP response from sms-over-xmpp isn't making it back to Twilio somehow. How is your server configured? Does Twilio talk directly to sms-over-xmpp or do you have a proxy in the middle? Does sms-over-xmpp show any error messages during these requests?

Also, any chance you could attach a screenshot of Twilio's Request Inspector for one of these requests?

Let me know and I'll see what I can figure out.
